import { useMemo, useState } from 'react';
import { useLocation } from 'wouter';
import { ArrowLeft, Bot, Play, Square, Trash2 } from 'lucide-react';
import { BottomNav } from '@/components/bottom-nav';

type Position={id:string;symbol:string;side:'매수'|'매도';qty:number;entry:number;current:number;target:number;stop:number;openedAt:string};
const KEY='sj-mock-auto-positions-v1';
function load():Position[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
export default function AutoTradePage(){
 const [,navigate]=useLocation(); const [running,setRunning]=useState(false); const [symbol,setSymbol]=useState('005930'); const [qty,setQty]=useState('1'); const [price,setPrice]=useState('70000'); const [targetPct,setTargetPct]=useState('5'); const [stopPct,setStopPct]=useState('3'); const [positions,setPositions]=useState<Position[]>(load);
 const preview=useMemo(()=>{const q=Number(qty),p=Number(price),t=Number(targetPct),s=Number(stopPct);if(![q,p,t,s].every(Number.isFinite)||q<=0||p<=0)return null;return {amount:q*p,target:p*(1+t/100),stop:p*(1-s/100)}},[qty,price,targetPct,stopPct]);
 const save=(next:Position[])=>{setPositions(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const simulate=()=>{if(!preview||!symbol.trim())return; const pos:Position={id:crypto.randomUUID(),symbol:symbol.trim().toUpperCase(),side:'매수',qty:Number(qty),entry:Number(price),current:Number(price),target:preview.target,stop:preview.stop,openedAt:new Date().toISOString()};save([pos,...positions]);};
 return <div className="h-full overflow-y-auto bg-background"><div className="mx-auto max-w-md px-4 pb-28 pt-4"><header className="grid grid-cols-[40px_1fr_40px] items-center"><button onClick={()=>navigate('/tech')} className="flex h-9 w-9 items-center justify-center rounded-full border border-card-border"><ArrowLeft className="h-4 w-4"/></button><div className="text-center"><h1 className="text-lg font-black">모의 자동매매</h1><p className="text-[11px] font-bold text-muted-foreground">관리자 전용 · 실주문 완전 차단</p></div><Bot className="h-5 w-5"/></header>
 <div className="mt-4 rounded-2xl border border-amber-500/40 bg-amber-500/10 p-3 text-xs font-black text-amber-600">실계좌 주문 API는 호출하지 않습니다. 모든 주문과 포지션은 이 기기의 모의 데이터로만 저장됩니다.</div>
 <section className="mt-4 rounded-3xl border border-card-border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-black">자동 실행 상태</h2><button onClick={()=>setRunning(!running)} className={`flex items-center gap-2 rounded-full px-4 py-2 text-xs font-black ${running?'bg-destructive text-white':'bg-primary text-primary-foreground'}`}>{running?<><Square className="h-3.5 w-3.5"/>중지</>:<><Play className="h-3.5 w-3.5"/>모의 시작</>}</button></div><p className="mt-2 text-xs font-bold text-muted-foreground">{running?'신호 조건을 감시하는 모의 상태입니다. 실제 주문은 발생하지 않습니다.':'현재 중지 상태입니다.'}</p></section>
 <section className="mt-4 space-y-3 rounded-3xl border border-card-border bg-card p-4"><h2 className="font-black">모의 주문 생성</h2><Field label="종목코드" value={symbol} set={setSymbol}/><div className="grid grid-cols-2 gap-2"><Field label="수량" value={qty} set={setQty}/><Field label="기준가" value={price} set={setPrice}/><Field label="목표 수익률 %" value={targetPct} set={setTargetPct}/><Field label="손절률 %" value={stopPct} set={setStopPct}/></div><div className="rounded-2xl bg-secondary p-3 text-xs font-bold"><Row a="예상금액" b={preview?`${preview.amount.toLocaleString()}원`:'산출 불가'}/><Row a="목표가" b={preview?Math.round(preview.target).toLocaleString():'-'}/><Row a="손절가" b={preview?Math.round(preview.stop).toLocaleString():'-'}/></div><button onClick={simulate} className="w-full rounded-2xl bg-primary py-3 text-sm font-black text-primary-foreground">모의 주문 추가</button></section>
 <section className="mt-4 rounded-3xl border border-card-border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-black">모의 포지션 {positions.length}건</h2>{positions.length>0&&<button onClick={()=>save([])} className="text-destructive"><Trash2 className="h-4 w-4"/></button>}</div><div className="mt-3 space-y-2">{positions.length===0?<div className="rounded-2xl bg-secondary p-5 text-center text-xs font-bold text-muted-foreground">포지션이 없습니다.</div>:positions.map(p=><div key={p.id} className="rounded-2xl border border-card-border p-3"><div className="flex justify-between"><span className="font-black">{p.symbol}</span><button onClick={()=>save(positions.filter(x=>x.id!==p.id))} className="text-xs font-black text-destructive">청산</button></div><div className="mt-2 grid grid-cols-2 gap-1 text-xs font-bold text-muted-foreground"><span>수량 {p.qty}</span><span>진입 {p.entry.toLocaleString()}</span><span>목표 {Math.round(p.target).toLocaleString()}</span><span>손절 {Math.round(p.stop).toLocaleString()}</span></div></div>)}</div></section></div><BottomNav/></div>
}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block"><span className="mb-1 block text-[11px] font-black text-muted-foreground">{label}</span><input value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border border-card-border bg-background px-3 py-2.5 text-sm font-black outline-none"/></label>}
function Row({a,b}:{a:string;b:string}){return <div className="flex justify-between py-1"><span className="text-muted-foreground">{a}</span><span className="font-black text-foreground">{b}</span></div>}
