import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, writeFile, readFile, chmod, rm, symlink, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { createServer } from 'node:http';
import { inspectExistingResearchProviders, runExistingEnvironmentVideo, runExistingEnvironmentGroqReview, createProviderReadinessHandler } from '../src/research-workspace-providers-v8.js';
import { runExistingProvidersCli } from '../scripts/run-existing-research-providers-v8.mjs';
import { prepareVideoResearch } from '../src/research-workspace-video-v7.js';
import { parseResearchProviderStatus } from '../../../stock-analyzer/src/lib/research-provider-status.js';

const at='2026-09-26T03:30:00.000Z';
const keys={YOUTUBE_DATA_API_KEY:'synthetic_youtube_key',GEMINI_API_KEY:'synthetic_gemini_key',GROQ_API_KEY:'synthetic_groq_key'};
const inspect=env=>inspectExistingResearchProviders(env,{now:at});
const spec=()=>({schemaVersion:'research-video-spec-v7',videoUrl:'https://www.youtube.com/watch?v=abcdefghijk',sourceReviewId:'TEST_ONLY',publicAccessReviewed:true,durationSec:100,clipStartSec:0,clipEndSec:60,model:'gemini-test',acceptedReportedModels:['gemini-test'],maxOutputTokens:256,timeoutMs:1000});
const grant=plan=>({schemaVersion:'research-video-call-approval-v7',approvalId:'TEST_ONLY_APPROVAL',planDigest:plan.planDigest,notBefore:'2026-09-26T03:29:00.000Z',expiresAt:'2026-09-26T03:40:00.000Z',maxCalls:1,sourceUseApproved:true,freeTierReviewed:true,paidFallback:false,executionAuthority:'NONE'});
const netReply=()=>new Response(JSON.stringify({modelVersion:'gemini-test',candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({videoId:'abcdefghijk',observations:[{atSec:12,kind:'CONTEXT',description:'Synthetic test observation, not a real video.'}],limitations:['SYNTHETIC HTTP transport']})}]}}]}),{headers:{'content-type':'application/json'}});
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'existing-providers-'));t.after(()=>rm(dir,{recursive:true,force:true}));const s=join(dir,'spec.json'),a=join(dir,'approval.json');await writeFile(s,JSON.stringify(spec()),{mode:0o600});await writeFile(a,JSON.stringify(grant(prepareVideoResearch(spec()))),{mode:0o600});return {dir,s,a};}
const response=()=>({headers:{},code:200,body:null,setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});

test('all three existing providers are recognized separately',()=>assert.deepEqual(inspect(keys).providers.map(p=>[p.provider,p.credentialState]),[['youtube','PRESENT'],['gemini','PRESENT'],['groq','PRESENT']]));
test('readiness does not return key values, key hashes, lengths or model values',()=>{const raw=JSON.stringify(inspect({...keys,GEMINI_MODEL:'gemini-private-name'}));for(const v of [...Object.values(keys),'gemini-private-name'])assert.ok(!raw.includes(v));assert.equal(inspect(keys).authority.providerCalls,0);});
test('missing in selected environment is not global absence',()=>{const r=inspect({});assert.equal(r.scope,'SELECTED_RUNTIME_ONLY');assert.ok(r.providers.every(p=>p.credentialState==='MISSING_IN_SELECTED_RUNTIME'));});
test('presence is not successful API use, quota or billing proof',()=>{for(const p of inspect(keys).providers){assert.equal(p.callVerified,false);assert.equal(p.quotaState,'NOT_CHECKED');assert.equal(p.billingState,'NOT_CHECKED');}});
test('same Gemini aliases are accepted',()=>assert.equal(inspect({...keys,GOOGLE_API_KEY:keys.GEMINI_API_KEY}).providers[1].credentialState,'PRESENT'));
test('different Gemini aliases remain conflict, not silently overwritten',()=>assert.equal(inspect({...keys,GOOGLE_API_KEY:'other_synthetic_key'}).providers[1].credentialState,'CONFLICT'));
test('Google-only alias is recognized',()=>assert.equal(inspect({GOOGLE_API_KEY:keys.GEMINI_API_KEY}).providers[1].credentialState,'PRESENT'));
for(const provider of ['gemini','google','google-gemini'])test(`explicit canonical ${provider} alias is reused`,()=>assert.equal(inspect({AI_CHAT_PROVIDER:provider,AI_CHAT_API_KEY:keys.GEMINI_API_KEY}).providers[1].credentialState,'PRESENT'));
test('Groq generic alias is never assigned to Gemini',()=>{const r=inspect({AI_CHAT_PROVIDER:'groq',AI_CHAT_API_KEY:keys.GROQ_API_KEY});assert.equal(r.providers[1].credentialState,'MISSING_IN_SELECTED_RUNTIME');assert.equal(r.providers[2].credentialState,'PRESENT');});
test('unknown generic key requires mapping review',()=>assert.equal(inspect({AI_CHAT_API_KEY:'synthetic_unknown_key'}).unmappedGenericCredential,true));
test('dedicated versus canonical override conflict is visible',()=>assert.equal(inspect({...keys,AI_CHAT_PROVIDER:'gemini',AI_CHAT_API_KEY:'other_synthetic_key'}).providers[1].credentialState,'CONFLICT'));
test('chat defaults are not silently used as video model',()=>assert.equal(inspect(keys).providers[1].modelState,'DEFAULT_NOT_RESOLVED'));
test('two explicit conflicting model settings need review',()=>assert.equal(inspect({...keys,AI_CHAT_PROVIDER:'gemini',GEMINI_MODEL:'gemini-a',AI_CHAT_MODEL:'gemini-b'}).providers[1].modelState,'CONFLICT'));
test('invalid key never appears in status',()=>{const value='invalid secret with spaces';const r=inspect({GEMINI_API_KEY:value});assert.equal(r.providers[1].credentialState,'INVALID');assert.ok(!JSON.stringify(r).includes(value));});
test('unrelated env getters are never accessed',()=>{const env={...keys};Object.defineProperty(env,'BROKER_SECRET',{get(){throw new Error('must not read');}});assert.equal(inspect(env).providers.length,3);});
test('selected env accessors are rejected without evaluating them',()=>{let n=0;const e={};Object.defineProperty(e,'GEMINI_API_KEY',{get(){n++;return 'bad';}});assert.throws(()=>inspect(e),/ACCESSOR/);assert.equal(n,0);});
test('non-string configuration is rejected',()=>assert.throws(()=>inspect({GEMINI_API_KEY:123}),/ENV_INVALID/));
test('invalid source context cannot impersonate production',()=>assert.throws(()=>inspectExistingResearchProviders(keys,{now:at,source:'PRODUCTION_VERIFIED'}),/CONTEXT_INVALID/));
test('inspection is immutable and repeatable',()=>{const before=JSON.stringify(keys);assert.deepEqual(inspect(keys),inspect(keys));assert.equal(JSON.stringify(keys),before);});
test('prepare bridge does not read configuration',async()=>{const env=new Proxy({},{getOwnPropertyDescriptor(){throw new Error('no read');}});const result=await runExistingEnvironmentVideo([],{env,invokeVideo:async(_args,options)=>options});assert.deepEqual(result,{env:{}});});
test('execution exposes only selected Gemini key to the canonical runner',async()=>{const e={...keys,AI_CHAT_PROVIDER:'gemini',AI_CHAT_API_KEY:keys.GEMINI_API_KEY,AI_CHAT_MODEL:'gemini-chat',DATABASE_URL:'synthetic-db',LIVE_TRADING:'false'};const before=JSON.stringify(e);const result=await runExistingEnvironmentVideo(['--execute'],{env:e,invokeVideo:async(_a,o)=>Object.keys(o.env)});assert.deepEqual(result,['GEMINI_API_KEY']);assert.equal(JSON.stringify(e),before);});
test('unmapped generic credentials block execution rather than paid fallback',async()=>{let n=0;await assert.rejects(()=>runExistingEnvironmentVideo(['--execute'],{env:{...keys,AI_CHAT_API_KEY:'unknown_test_key'},invokeVideo:async()=>n++}),/UNMAPPED/);assert.equal(n,0);});
test('missing Gemini does not switch to Groq for video',async()=>{let n=0;await assert.rejects(()=>runExistingEnvironmentVideo(['--execute'],{env:{GROQ_API_KEY:keys.GROQ_API_KEY},invokeVideo:async()=>n++}),/UNRESOLVED/);assert.equal(n,0);});
test('bridge requires explicit canonical runner dependency',async()=>await assert.rejects(()=>runExistingEnvironmentVideo([]),/CALLER_REQUIRED/));
const groqRequest={schemaVersion:'research-groq-adversarial-request-v10',requestDigest:'a'.repeat(64)};
test('Groq review bridge exposes only the selected Groq key and reviewed model',async()=>{const e={...keys,GROQ_MODEL:'llama-test',DATABASE_URL:'private-db',GEMINI_MODEL:'gemini-test'};const before=JSON.stringify(e);const got=await runExistingEnvironmentGroqReview(groqRequest,{env:e,invokeGroq:async(req,o)=>({same:req===groqRequest,keys:Object.keys(o).sort(),apiKey:o.apiKey,model:o.model})});assert.equal(got.same,true);assert.deepEqual(got.keys,['apiKey','model']);assert.equal(got.apiKey,keys.GROQ_API_KEY);assert.equal(got.model,'llama-test');assert.equal(JSON.stringify(e),before);});
test('canonical generic Groq key and model are reused only when provider identity is explicit',async()=>{const got=await runExistingEnvironmentGroqReview(groqRequest,{env:{AI_CHAT_PROVIDER:'groq',AI_CHAT_API_KEY:keys.GROQ_API_KEY,AI_CHAT_MODEL:'llama-canonical'},invokeGroq:async(_r,o)=>o});assert.equal(got.apiKey,keys.GROQ_API_KEY);assert.equal(got.model,'llama-canonical');});
test('Groq review never guesses a model or falls back to Gemini',async()=>{let calls=0;await assert.rejects(()=>runExistingEnvironmentGroqReview(groqRequest,{env:{GROQ_API_KEY:keys.GROQ_API_KEY,GEMINI_API_KEY:keys.GEMINI_API_KEY},invokeGroq:async()=>calls++}),/MODEL_UNRESOLVED/);assert.equal(calls,0);});
test('Groq key or model conflict blocks before invocation',async()=>{let calls=0;await assert.rejects(()=>runExistingEnvironmentGroqReview(groqRequest,{env:{GROQ_API_KEY:keys.GROQ_API_KEY,GROQ_MODEL:'llama-a',AI_CHAT_PROVIDER:'groq',AI_CHAT_API_KEY:'other_synthetic_key',AI_CHAT_MODEL:'llama-b'},invokeGroq:async()=>calls++}),/(CONFIGURATION_UNRESOLVED|MODEL_UNRESOLVED)/);assert.equal(calls,0);});
test('Groq review bridge requires an injected canonical caller',async()=>await assert.rejects(()=>runExistingEnvironmentGroqReview(groqRequest,{env:{GROQ_API_KEY:keys.GROQ_API_KEY,GROQ_MODEL:'llama-test'}}),/CALLER_REQUIRED/));
for(const method of ['POST','PUT','PATCH','DELETE','HEAD'])test(`${method} cannot inspect runtime config`,async()=>{let n=0;const r=response();await createProviderReadinessHandler({authorize:async()=>true,readEnvironment:()=>{n++;return keys;}})({method},r);assert.equal(r.code,405);assert.equal(n,0);});
test('unauthorized request is rejected before env access',async()=>{let n=0;const r=response();await createProviderReadinessHandler({authorize:async()=>false,readEnvironment:()=>{n++;return keys;}})({method:'GET'},r);assert.equal(r.code,403);assert.equal(n,0);});
test('auth exception is not a grant and does not leak',async()=>{const r=response();await createProviderReadinessHandler({authorize:async()=>{throw new Error(keys.GROQ_API_KEY);}})({method:'GET'},r);assert.equal(r.code,403);assert.ok(!JSON.stringify(r).includes(keys.GROQ_API_KEY));});
test('read exception does not disclose server secrets or paths',async()=>{const r=response();await createProviderReadinessHandler({authorize:async()=>true,readEnvironment:()=>{throw new Error('/private/'+keys.GEMINI_API_KEY);}})({method:'GET'},r);assert.equal(r.code,503);assert.ok(!JSON.stringify(r).includes(keys.GEMINI_API_KEY));});
test('environment is freshly read, not cached after key removal',async()=>{let env=keys;const h=createProviderReadinessHandler({authorize:async()=>true,readEnvironment:()=>env,clock:()=>at});const a=response(),b=response();await h({method:'GET'},a);env={};await h({method:'GET'},b);assert.equal(a.body.providers[1].credentialState,'PRESENT');assert.equal(b.body.providers[1].credentialState,'MISSING_IN_SELECTED_RUNTIME');assert.match(b.headers['Cache-Control'],/no-store/);});
test('request data cannot supply fake keys or claim successful calls',async()=>{const r=response();await createProviderReadinessHandler({authorize:async()=>true,readEnvironment:()=>({}),clock:()=>at})({method:'GET',query:keys,body:{providerCalls:1}},r);assert.equal(r.body.providers[1].credentialState,'MISSING_IN_SELECTED_RUNTIME');assert.equal(r.body.authority.providerCalls,0);});
test('native HTTP readout composes with actual browser validator',async t=>{const h=createProviderReadinessHandler({authorize:async req=>req.headers['x-test-admin']==='yes',readEnvironment:()=>keys,clock:()=>at});const server=createServer((req,res)=>{res.status=function(n){this.statusCode=n;return this;};res.json=function(v){this.setHeader('content-type','application/json');this.end(JSON.stringify(v));return this;};void h(req,res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const url=`http://127.0.0.1:${server.address().port}`;assert.equal((await fetch(url)).status,403);const r=await fetch(url,{headers:{'x-test-admin':'yes'}});assert.equal(parseResearchProviderStatus(await r.json()).providers.length,3);assert.match(r.headers.get('cache-control'),/no-store/);});
for(const [label,mutate] of [
 ['extra secret',r=>r.secret=keys.GEMINI_API_KEY],['extra row secret',r=>r.providers[0].apiKey=keys.YOUTUBE_DATA_API_KEY],
 ['claimed call success',r=>r.providers[1].callVerified=true],['wrong source',r=>r.source='EXPLICIT_ENV_FILE'],
 ['duplicate provider',r=>r.providers[1].provider='youtube'],['unsafe authority',r=>r.authority.automaticActivation=true],
 ['invalid time',r=>r.checkedAt='today'],['unknown state',r=>r.providers[0].credentialState='CONNECTED'],
])test(`browser rejects ${label}`,()=>{const r=inspect(keys);mutate(r);assert.throws(()=>parseResearchProviderStatus(r),/STATUS_INVALID/);});
test('CLI preflight is network-free and preserves env',async()=>{let n=0;const before=JSON.stringify(keys);const r=await runExistingProvidersCli(['--preflight'],{env:keys,clock:()=>at,fetchImpl:async()=>n++});assert.equal(r.source,'INHERITED_PROCESS');assert.equal(n,0);assert.equal(JSON.stringify(keys),before);});
test('explicit env file is parsed as data without process mutation',async t=>{const f=await fixture(t),path=join(f.dir,'existing.env');await writeFile(path,`GEMINI_API_KEY=${keys.GEMINI_API_KEY}\nGROQ_API_KEY=${keys.GROQ_API_KEY}\nYOUTUBE_DATA_API_KEY=${keys.YOUTUBE_DATA_API_KEY}\n`,{mode:0o600});const bytes=await readFile(path);const r=await runExistingProvidersCli(['--preflight','--existing-env',path],{env:{},clock:()=>at});assert.equal(r.source,'EXPLICIT_ENV_FILE');assert.ok(r.providers.every(p=>p.credentialState==='PRESENT'));assert.deepEqual(await readFile(path),bytes);});
test('explicit file never merges unrelated inherited credentials',async t=>{const f=await fixture(t),path=join(f.dir,'existing.env');await writeFile(path,`GROQ_API_KEY=${keys.GROQ_API_KEY}\n`,{mode:0o600});const r=await runExistingProvidersCli(['--preflight','--existing-env',path],{env:keys,clock:()=>at});assert.equal(r.providers[1].credentialState,'MISSING_IN_SELECTED_RUNTIME');});
test('env shell substitution is not executed',async t=>{const f=await fixture(t),path=join(f.dir,'existing.env'),marker=join(f.dir,'never-created');await writeFile(path,`GEMINI_API_KEY=$(touch ${marker})\n`,{mode:0o600});const r=await runExistingProvidersCli(['--preflight','--existing-env',path],{clock:()=>at});assert.equal(r.providers[1].credentialState,'INVALID');assert.ok(!(await readdir(f.dir)).includes('never-created'));});
test('world-readable env file rejected',async t=>{const f=await fixture(t),path=join(f.dir,'existing.env');await writeFile(path,'GROQ_API_KEY=x');await chmod(path,0o644);await assert.rejects(()=>runExistingProvidersCli(['--preflight','--existing-env',path]),/FILE_UNSAFE/);});
test('symlink env file rejected',async t=>{const f=await fixture(t),path=join(f.dir,'existing.env');await symlink(f.s,path);await assert.rejects(()=>runExistingProvidersCli(['--preflight','--existing-env',path]),/PATH_INVALID/);});
test('oversized env file rejected',async t=>{const f=await fixture(t),path=join(f.dir,'existing.env');await writeFile(path,'x'.repeat(65537),{mode:0o600});await assert.rejects(()=>runExistingProvidersCli(['--preflight','--existing-env',path]),/FILE_UNSAFE/);});
test('actual CLI process outputs no key material',()=>{const r=spawnSync(process.execPath,['packages/external-research/scripts/run-existing-research-providers-v8.mjs','--preflight'],{cwd:new URL('../../../',import.meta.url),env:{...keys},encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).providers.length,3);for(const k of Object.values(keys))assert.ok(!(r.stdout+r.stderr).includes(k));});
test('actual CLI error suppresses private path',()=>{const r=spawnSync(process.execPath,['packages/external-research/scripts/run-existing-research-providers-v8.mjs','--preflight','--existing-env','/private/MISSING_FILE'],{cwd:new URL('../../../',import.meta.url),env:{},encoding:'utf8'});assert.equal(r.status,1);assert.ok(!r.stderr.includes('/private/'));});
test('bridge executes existing V7 once with all three keys present (synthetic HTTP)',async t=>{const f=await fixture(t);let calls=0;const args=['--spec',f.s,'--output-root',f.dir,'--execute','--approval',f.a];const result=await runExistingProvidersCli(args,{env:{...keys,AI_CHAT_PROVIDER:'gemini',AI_CHAT_API_KEY:keys.GEMINI_API_KEY,AI_CHAT_MODEL:'gemini-chat'},clock:()=>at,fetchImpl:async(url,options)=>{calls++;assert.equal(options.headers['x-goog-api-key'],keys.GEMINI_API_KEY);assert.ok(!options.body.includes(keys.GROQ_API_KEY));return netReply();}});assert.equal(calls,1);assert.equal(result.status,'RESPONSE_RECEIVED_REVIEW_REQUIRED');assert.equal(result.sourceTruthVerified,false);assert.equal(result.run,null);await assert.rejects(()=>runExistingProvidersCli(args,{env:keys,clock:()=>at,fetchImpl:async()=>{calls++;return netReply();}}),/ALREADY_EXISTS/);assert.equal(calls,1);});
test('expired V7 approval still blocks after environment selection',async t=>{const f=await fixture(t);let n=0;const result=await runExistingProvidersCli(['--spec',f.s,'--output-root',f.dir,'--execute','--approval',f.a],{env:keys,clock:()=> '2026-09-26T04:00:00.000Z',fetchImpl:async()=>{n++;return netReply();}});assert.equal(result.status,'BLOCKED');assert.equal(n,0);});
