import assert from 'node:assert/strict';
import test from 'node:test';
import { adaptCrossrefMetadata } from '../src/index.js';
import { createResearchVideoSourceV1 } from '../src/video-intelligence.js';
import { createResearchRuntimeBindingV11,researchRuntimeRuleDigestV11 } from '../src/research-workspace-runtime-binding-v11.js';

const paper=()=>adaptCrossrefMetadata({status:'ok','message-type':'work','message-version':'1.0.0',message:{DOI:'10.1234/runtime.v11',title:['Runtime binding evidence'],author:[{given:'Ada',family:'Lovelace'}],published:{'date-parts':[[2025,1,2]]},indexed:{'date-time':'2026-09-20T00:00:00Z',version:'3.51.4'},license:[{URL:'https://creativecommons.org/licenses/by/4.0/','content-version':'vor','delay-in-days':0,start:{'date-parts':[[2025,1,2]]}}]}},{retrievedAt:'2026-09-25T00:00:00.000Z',retrievedFrom:'https://api.crossref.org/v1/works/10.1234/runtime.v11'});
const source=()=>createResearchVideoSourceV1({provider:'YOUTUBE',sourceType:'YOUTUBE_VIDEO',canonicalUrl:'https://www.youtube.com/watch?v=abcdefghijk',videoId:'abcdefghijk',title:'Synthetic reviewed strategy',channelOrPublisher:'Test',publishedAt:'2026-09-20T00:00:00.000Z',discoveredAt:'2026-09-25T00:00:00.000Z',language:'en',durationSec:120,transcriptStatus:'AVAILABLE',transcriptSource:'REVIEWED_TEST_TRANSCRIPT',transcriptAuthorized:true,contentAccessStatus:'AVAILABLE',timestampProvenance:[]});
const gemini={observations:['ENTRY','EXIT','STOP_LOSS','POSITION_SIZING','EXECUTION_ASSUMPTION'].map((kind,i)=>({atSec:10+i,kind,description:'Synthetic '+kind.toLowerCase()+' rule',origin:'MODEL_OBSERVATION',semanticReview:'PENDING',timestampVerified:false})),limitations:['Synthetic only']};
const groq={findings:gemini.observations.map((_,i)=>({observationIndex:i,verdict:'ACCEPT_AS_CLAIM',reason:'Synthetic reviewed claim'}))};
const baseConfig=()=>{
 const p=paper(),reviewedRuleDigest=researchRuntimeRuleDigestV11(gemini,groq);
 return {source:source(),trustedContext:{reviewedRuleDigest,market:'US_STOCK',side:'LONG',timeframe:'1h',strategyFamily:'TREND_ADX',categories:['TREND_FOLLOWING'],symbolScope:['SPY']},
 crossValidation:{supportingPapers:[p],contradictoryPapers:[],officialSources:[]},
 canonicalCore:{title:'Reviewed runtime hypothesis',statement:'Reviewed rules may justify bounded research.',rationale:'Research only.',evidenceStrength:{supporting:'STRONG',contradictory:'NONE'},expectedEffect:{observable:'NEXT_WINDOW_EXCESS_RETURN',direction:'INCREASE',minimumMagnitude:null,unit:'DECIMAL_RETURN',evaluationWindow:'1h'},falsificationCriteria:{observable:'NEXT_WINDOW_EXCESS_RETURN',metric:'MEAN_CONDITIONAL_EXCESS_RETURN',operator:'LTE',threshold:0,unit:'DECIMAL_RETURN',evaluationWindow:'1h',minimumObservations:200,rejectionStatement:'Reject when non-positive.'},requiredData:[{dataset:'LICENSED_INTRADAY_EQUITY_BARS',fields:['security_id','open','high','low','close','volume'],frequency:'1h',provenanceRequired:true,licenseRequired:true}],knownLimitations:['Research only.'],createdAt:'2026-09-26T06:00:00.000Z',generator:{name:'runtime-v11',version:'1.0.0'},evidencePolicy:{requireKnownContentLicense:true,requireResolvedCorrections:true}},
 committeeReview:{rationale:'Approved for bounded research only.',decidedAt:'2026-09-26T06:01:00.000Z',committee:{name:'Research Committee',version:'1.0.0',members:['reviewer-a']}},
 seedProfile:{profileId:'US_STOCK:SWING',market:'US_STOCK',horizon:'SWING',timeframe:'1h',directions:['LONG'],status:'BLOCKED_DATA',formulaFamilies:[],requiredDerivativesEvidence:[],blockers:['TEST_BLOCK']},
 templates:[],catalogSafety:{researchCandidateOnly:true,tournamentValidationRequired:true,profitabilityClaimAllowed:false,formulaPassed:false,scannerRuntimeMutationAllowed:false,liveTrading:false,autoTrading:false,realOrderEnabled:false,privateTradingApiAllowed:false,executionAuthority:'NONE'},
 compilerPolicy:{datasetIdentity:'dataset:test'},candidatesPerFormula:1,tournament:{}};
};
test('review digest is stable and changes when a Groq verdict changes',()=>{const a=researchRuntimeRuleDigestV11(gemini,groq);const changed=structuredClone(groq);changed.findings[0].verdict='CHALLENGE';assert.match(a,/^[a-f0-9]{64}$/);assert.notEqual(a,researchRuntimeRuleDigestV11(gemini,changed));});
test('binding rejects rule set that was not explicitly reviewed',async()=>{const c=baseConfig();c.trustedContext.reviewedRuleDigest='f'.repeat(64);const b=createResearchRuntimeBindingV11(c);const out=await b.compileCanonical({plan:{planDigest:'a'.repeat(64)},geminiReceipt:gemini,groqReview:groq,ruleAssessment:{status:'COMPLETE'}});assert.equal(out.status,'REVIEW_REQUIRED');assert.equal(out.reason,'RULE_REVIEW_DIGEST_MISMATCH');});
test('binding preserves no execution/profitability authority',()=>{const b=createResearchRuntimeBindingV11(baseConfig());assert.equal(b.authority.executionAuthority,'NONE');assert.equal(b.authority.automaticAdoption,false);assert.equal(b.authority.profitabilityProven,false);});
