import test from 'node:test';
import assert from 'node:assert/strict';
import { createResearchVideoSourceV1 } from '../src/video-intelligence.js';
import {
  bindAuthorizedTranscriptToSourceV2,
  createYoutubeDiscoveryClientV2,
  extractStrategyRulesV2,
  extractTranscriptClaimsV2,
  normalizeAuthorizedTranscriptV2,
} from '../src/video-intelligence-phase2.js';

const NOW='2026-09-12T09:30:00.000Z';
const response=(body,status=200)=>({ok:status>=200&&status<300,status,async json(){return body;}});
function source(){return createResearchVideoSourceV1({provider:'YOUTUBE',sourceType:'YOUTUBE_VIDEO',canonicalUrl:'https://www.youtube.com/watch?v=fixture-a',videoId:'fixture-a',title:'Momentum lecture',channelOrPublisher:'Research Channel',publishedAt:'2026-09-11T00:00:00Z',discoveredAt:NOW,language:'en',durationSec:600,transcriptStatus:'NOT_AUTHORIZED',transcriptSource:null,transcriptAuthorized:false,contentAccessStatus:'AVAILABLE',timestampProvenance:[]});}
function transcript(s=source()){return normalizeAuthorizedTranscriptV2({source:s,status:'AVAILABLE',transcriptSource:'AUTHORIZED_FIXTURE',authorized:true,language:'en',segments:[{startSec:10,endSec:20,text:'On US stocks use the 15 minute chart and enter long when price reclaims VWAP.',source:'AUTHORIZED_FIXTURE'},{startSec:21,endSec:30,text:'Exit when price closes back below VWAP.',source:'AUTHORIZED_FIXTURE'}]});}

test('official discovery maps metadata without transcript authority',async()=>{const calls=[];const fetchImpl=async url=>{calls.push(String(url));if(String(url).includes('/search?'))return response({items:[{id:{videoId:'abc123'},snippet:{title:'VWAP lesson',channelId:'channel-1',channelTitle:'Research Channel',publishedAt:'2026-09-10T00:00:00Z'}}]});return response({items:[{id:'abc123',snippet:{title:'VWAP lesson',channelId:'channel-1',channelTitle:'Research Channel',publishedAt:'2026-09-10T00:00:00Z',description:'Education',defaultAudioLanguage:'en'},contentDetails:{duration:'PT10M',caption:'true'}}]});};const client=createYoutubeDiscoveryClientV2({apiKey:'k',fetchImpl,limits:{maxResultsPerQuery:5,maxPagesPerRun:1,maxVideosPerResearchBatch:5}});const result=await client.discover({query:'vwap research',maxResults:5,maxPages:1,discoveredAt:NOW});assert.equal(result.status,'SUCCESS');assert.equal(result.records.length,1);assert.equal(result.records[0].source.transcriptStatus,'NOT_AUTHORIZED');assert.equal(result.records[0].economicEvidenceCredit,0);assert.equal(calls.length,2);assert.equal(client.automaticDiscoveryEnabled,false);});

test('provider unavailable states never become empty success',async()=>{const missing=await createYoutubeDiscoveryClientV2().discover({query:'momentum',discoveredAt:NOW});assert.equal(missing.status,'PROVIDER_NOT_CONFIGURED');assert.deepEqual(missing.records,[]);const rate=createYoutubeDiscoveryClientV2({apiKey:'k',fetchImpl:async()=>response({},429)});assert.equal((await rate.discover({query:'x',discoveredAt:NOW})).status,'RATE_LIMITED');});

test('authorized transcript preserves timestamps and strategy fields require claim provenance',async()=>{const raw=source(),t=transcript(raw),bound=bindAuthorizedTranscriptToSourceV2({source:raw,transcript:t});assert.equal(t.segments[0].startSec,10);assert.match(t.segments[0].contentHash,/^[0-9a-f]{64}$/u);const claims=await extractTranscriptClaimsV2({transcript:t,extractor:({segments})=>[{segmentId:segments[0].segmentId,claimType:'STRATEGY_RULE',text:'US stock 15m VWAP reclaim long entry',uncertainty:'RULE_EXPLICIT'},{segmentId:segments[1].segmentId,claimType:'STRATEGY_RULE',text:'Exit below VWAP',uncertainty:'RULE_EXPLICIT'}]});const mined=await extractStrategyRulesV2({source:bound,transcript:t,claimResult:claims,extractor:({claims:rows})=>({market:'US_STOCK',assetClass:'EQUITY',symbolScope:['US_STOCK'],side:'LONG',timeframe:'15m',strategyFamily:'VWAP_RECLAIM',categories:['TECHNICAL_ANALYSIS'],holdingPeriod:null,executionAssumptions:[],fieldProvenance:{market:rows[0].claimId,assetClass:rows[0].claimId,symbolScope:rows[0].claimId,side:rows[0].claimId,timeframe:rows[0].claimId,strategyFamily:rows[0].claimId,categories:rows[0].claimId},rules:[{claimId:rows[0].claimId,ruleType:'ENTRY',normalizedRule:'close reclaims VWAP',semanticKey:'VWAP_RECLAIM',polarity:'REQUIRE'},{claimId:rows[1].claimId,ruleType:'EXIT',normalizedRule:'close falls below VWAP',semanticKey:'VWAP_LOSS',polarity:'REQUIRE'}]})});assert.equal(mined.testability.status,'TESTABLE');assert.equal(mined.testability.inventedRuleCount,0);assert.deepEqual(mined.hypothesis.stopLossRules,[]);assert.deepEqual(mined.hypothesis.takeProfitRules,[]);});
