import {useEffect,useState} from 'react';
import {generateTradingAiReview,previewTradingAiReview,type AiReviewPreview,type GeneratedAiReview} from '@/lib/paper-journal-sync';
import {deleteSavedAiReviews,exportSavedAiReviews,loadSavedAiReviews,saveAiReview} from '@/lib/trading-ai-review-storage';
const button='min-h-11 rounded-xl border border-border px-4 text-sm font-bold disabled:opacity-40';
export function TradingAiReviewPanel({userId,periodStart,periodEnd}:{userId:string;periodStart:string;periodEnd:string}){const[preview,setPreview]=useState<AiReviewPreview|null>(null),[review,setReview]=useState<GeneratedAiReview|null>(null),[consent,setConsent]=useState(false),[style,setStyle]=useState<'concise'|'detailed'>('concise'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState<GeneratedAiReview[]>([]),[controller,setController]=useState<AbortController|null>(null);useEffect(()=>{setConsent(false);setPreview(null);setReview(null);setSaved(loadSavedAiReviews(localStorage,userId));},[userId]);
async function prepare(){setBusy(true);setError('');try{setPreview(await previewTradingAiReview(periodStart||undefined,periodEnd||undefined));setConsent(false);}catch(e){setError(e instanceof Error?e.message:'미리보기에 실패했습니다.');}finally{setBusy(false)}}
async function generate(){if(!consent||busy)return;const c=new AbortController();setController(c);setBusy(true);setError('');try{setReview(await generateTradingAiReview({periodStart:periodStart||undefined,periodEnd:periodEnd||undefined,consent:true,reviewStyle:style,idempotencyKey:`review:${Date.now()}`},c.signal));}catch(e){setError(e instanceof Error?e.message:'AI 복기에 실패했습니다.');}finally{setBusy(false);setController(null)}}
function download(){const blob=new Blob([exportSavedAiReviews(localStorage,userId)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='paper-trading-ai-reviews.json';a.click();URL.revokeObjectURL(url)}
return <section className="rounded-2xl border border-border bg-card p-4 space-y-4" data-testid="ai-review-panel"><header><h2 className="font-black">AI 거래 복기</h2><p className="text-sm text-muted-foreground">AI 복기는 과거 모의거래 기록을 바탕으로 한 학습용 분석이며 투자 조언이 아닙니다.</p><p className="text-sm font-semibold">AI는 실제 주문을 생성하거나 거래소에 주문을 전송하지 않습니다.</p></header><button className={button} disabled={busy} onClick={()=>void prepare()} data-testid="ai-review-preview">전송 payload 미리보기</button>{preview?<div className="rounded-xl bg-muted p-3 text-xs" data-testid="ai-review-preview-result"><p>기간: {preview.dataset.periodStart} ~ {preview.dataset.periodEnd}</p><p>거래: {preview.dataset.sampleSize}건 / 대표 {preview.dataset.representativeTrades.length}건</p><p>포함: {preview.includedFields.join(', ')}</p><p>제외: {preview.excludedFields.join(', ')}</p><p>외부 AI 호출: 아직 호출하지 않음</p></div>:null}{preview?<><label className="flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} />개인정보를 제외한 거래 요약 데이터를 외부 AI에 전송하는 데 동의합니다.</label><label className="text-sm">복기 방식 <select value={style} onChange={e=>setStyle(e.target.value as any)} className="rounded border bg-background p-2"><option value="concise">간결</option><option value="detailed">상세</option></select></label><div className="flex gap-2"><button className={button} disabled={!consent||busy} onClick={()=>void generate()} data-testid="ai-review-generate">{busy?'생성 중':'AI 복기 생성'}</button>{busy?<button className={button} onClick={()=>controller?.abort()}>취소</button>:null}</div></>:null}{error?<p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>:null}{review?<article className="space-y-3" data-testid="ai-review-result"><h3 className="font-bold">요약</h3><p>{review.result.summary}</p><h3 className="font-bold">잘한 점</h3>{review.result.strengths.map(x=><p key={x.title}>{x.title} · {x.explanation} · {x.confidence} · {x.evidenceIds.join(', ')}</p>)}<h3 className="font-bold">위험 패턴</h3>{review.result.riskPatterns.map(x=><p key={x.title}>{x.title} · {x.certainty} · {x.explanation}</p>)}<h3 className="font-bold">연습 행동</h3>{review.result.practiceActions.map(x=><p key={x.action}>{x.priority}. {x.action} — {x.measurableTarget}</p>)}<h3 className="font-bold">다음 거래 체크리스트</h3><ul>{review.result.nextTradeChecklist.map(x=><li key={x}>• {x}</li>)}</ul><p className="text-xs">{review.result.disclaimer}</p><button className={button} onClick={()=>setSaved(saveAiReview(localStorage,userId,review))}>이 브라우저에 저장</button></article>:null}<footer className="text-xs text-muted-foreground"><p>AI 복기 결과는 현재 이 브라우저에만 저장됩니다. 저장 {saved.length}건</p><div className="flex gap-2 mt-2"><button className={button} disabled={!saved.length} onClick={download}>JSON export</button><button className={button} disabled={!saved.length} onClick={()=>{deleteSavedAiReviews(localStorage,userId);setSaved([])}}>저장 결과 삭제</button></div></footer></section>}
