import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryProfitTelegramOutbox, ProfitFirstTelegramReportService, renderProfitFirstTelegramReport, splitTelegramText, type ProfitTelegramTransport } from './profit-first-telegram-report.service';
import type { AiEvidenceSnapshot } from './profit-first-ai-evidence.service';

function evidenceSnapshot(): AiEvidenceSnapshot {
  const signal = Object.freeze({ signalId: 's1', timestamp: '2026-08-13T09:00:00Z', market: 'KR_STOCK', symbol: '005930', symbolName: '삼성전자', strategyHorizon: 'SWING', direction: 'BUY', signalScore: 84, displayConfidence: null, referencePrice: 78200, entryPrice: 78200, stopLoss: 76900, target1: 80500, target2: 82300, riskReward: 2.2, timeframes: ['4H'], strategyProfileVersion: 'v1', indicatorSnapshot: {}, indicatorScores: {}, patternSnapshot: {}, volumeContext: {}, volatilityContext: {}, trendContext: {}, marketRegime: 'UPTREND', liquidityContext: {}, aiValidatorResult: null, riskEngineResult: { pass: true }, dataProvenance: ['runtime'], dataTimestamp: '2026-08-13T09:00:00Z', immutable: true, executionAuthority: 'NONE', profitEvidenceStatus: 'READY', profitProbability: 66.8, targetBeforeStopProbability: 65, lossProbability: 33.2, expectedGrossReturn: 3.4, expectedNetReturn: 3.1, expectedLoss: 1.2, expectedValue: 1.4, profitSampleSize: 1284, profitConfidenceInterval: [64, 69], tradingCostPolicyId: 'kr-v1' } as const);
  return Object.freeze({ signal: signal as any, evidence: Object.freeze({ news: { status: 'READY', quality: 'RECENT', items: [{ title: '공급계약', summary: '요약', publishedAt: '2026-08-13T08:00:00Z', source: 'n', reference: 'https://n', symbol: '005930', retrievedAt: '2026-08-13T09:00:00Z', provider: 'NAVER_OPEN_API' }], latencyMs: 1, retrievedAt: '2026-08-13T09:00:00Z' }, disclosure: { status: 'NO_RECENT_DISCLOSURE', quality: 'RECENT', items: [], riskEvents: [], latencyMs: 1, retrievedAt: '2026-08-13T09:00:00Z' }, chart: { status: 'READY', quality: 'RECENT', symbol: '005930', market: 'KR_STOCK', strategyMode: 'SWING', timeframe: '4H', signalId: 's1', trend: {}, support: null, resistance: null, entry: 78200, stop: 76900, targets: [80500, 82300], volumeContext: {}, volatilityContext: {}, candleSummary: {}, image: null, imageStatus: 'CHART_IMAGE_UNAVAILABLE', retrievedAt: '2026-08-13T09:00:00Z' } } as any), ai: Object.freeze({ status: 'READY', model: 'gemini-3.5-flash', latencyMs: 1, executionAuthority: 'NONE', validation: { validationResult: 'PASS', technicalAssessment: 'SUPPORT', newsAssessment: 'SUPPORT', disclosureAssessment: 'NO_DATA', riskFlags: [], bullishEvidence: [], bearishEvidence: [], criticalEvidence: [], summary: 'ok', confidence: 80 } }), immutable: true, executionAuthority: 'NONE' });
}

const recipient = { userId: 'u1', telegramChatId: 'chat1', enabled: true };

test('report uses evidence values, separates actual profit probability from AI confidence and includes no-guarantee warning', () => { const text = renderProfitFirstTelegramReport(evidenceSnapshot()); assert.match(text, /실제 수익확률 66.8%/); assert.match(text, /AI Validator\nPASS/); assert.doesNotMatch(text, /AI.*66.8%/); assert.match(text, /수익을 보장하지 않음/); });

test('successful send uses existing Telegram transport abstraction and marks outbox SENT', async () => { const outbox = new InMemoryProfitTelegramOutbox(); let sends = 0; const transport: ProfitTelegramTransport = { send: async () => { sends++; return { ok: true }; } }; const svc = new ProfitFirstTelegramReportService(outbox, transport); const queued = await svc.queue({ recipient, decision: 'FINAL_RECOMMENDATION', snapshot: evidenceSnapshot() }); assert.equal(queued.queued, true); const result = await svc.process({ recipient, deliveryId: queued.deliveryId! }); assert.equal(result.state, 'SENT'); assert.equal(sends, 1); });

test('duplicate is blocked and NO_TRADE/WATCH/Risk rejected are never sent as BUY', async () => { const outbox = new InMemoryProfitTelegramOutbox(); const transport: ProfitTelegramTransport = { send: async () => ({ ok: true }) }; const svc = new ProfitFirstTelegramReportService(outbox, transport, 0); const first = await svc.queue({ recipient, decision: 'FINAL_RECOMMENDATION', snapshot: evidenceSnapshot() }); assert.equal(first.queued, true); const duplicate = await svc.queue({ recipient, decision: 'FINAL_RECOMMENDATION', snapshot: evidenceSnapshot() }); assert.equal(duplicate.reason, 'DUPLICATE'); for (const decision of ['NO_TRADE','WATCH_ONLY','REJECTED_BY_RISK','AI_EVIDENCE_INCOMPLETE'] as const) assert.equal((await svc.queue({ recipient, decision, snapshot: evidenceSnapshot() })).queued, false); });

test('photo unavailable falls back to text and long reports split without losing content', async () => { assert.deepEqual(splitTelegramText('x'.repeat(9000)).map((x) => x.length), [4096, 4096, 808]); const outbox = new InMemoryProfitTelegramOutbox(); let sends = 0; const transport: ProfitTelegramTransport = { send: async () => { sends++; return { ok: true }; } }; const svc = new ProfitFirstTelegramReportService(outbox, transport); const queued = await svc.queue({ recipient, decision: 'FINAL_RECOMMENDATION', snapshot: evidenceSnapshot() }); await svc.process({ recipient, deliveryId: queued.deliveryId! }); assert.ok(sends >= 1); });

test('photo transport failure is retryable and scanner flow remains independent', async () => { const outbox = new InMemoryProfitTelegramOutbox(); const withPhoto = { ...evidenceSnapshot(), evidence: { ...evidenceSnapshot().evidence, chart: { ...evidenceSnapshot().evidence.chart, image: { mimeType: 'image/png', base64: 'AA==' }, imageStatus: 'AVAILABLE' as const } } } as AiEvidenceSnapshot; const transport: ProfitTelegramTransport = { send: async () => ({ ok: true }), sendPhoto: async () => ({ ok: false, errorCode: '429' }) }; const svc = new ProfitFirstTelegramReportService(outbox, transport); const queued = await svc.queue({ recipient, decision: 'FINAL_RECOMMENDATION', snapshot: withPhoto }); const result = await svc.process({ recipient, deliveryId: queued.deliveryId! }); assert.equal(result.state, 'RETRY_SCHEDULED'); });

test('unconfigured recipient fails closed without transport call', async () => { let called = false; const svc = new ProfitFirstTelegramReportService(new InMemoryProfitTelegramOutbox(), { send: async () => { called = true; return { ok: true }; } }); const result = await svc.queue({ recipient: { userId: 'u1', telegramChatId: null, enabled: true }, decision: 'FINAL_RECOMMENDATION', snapshot: evidenceSnapshot() }); assert.equal(result.reason, 'NOT_CONFIGURED'); assert.equal(called, false); });
