import type { ScannerStrategyMode } from './scanner-signal.types';

export type ScannerSignalDecayState = 'ACTIVE' | 'WEAKENED' | 'EXPIRED' | 'INVALID';

export type ScannerSignalDecaySnapshot = {
  signalCreatedAt: string;
  signalAgeMs: number;
  estimatedHalfLifeMs: number;
  edgeRemaining: number;
  expiresAt: string;
  strategyMode: ScannerStrategyMode | null;
  state: ScannerSignalDecayState;
  basis: 'TIME_VALIDITY_ONLY';
  financialProbability: false;
  orderAuthority: false;
};

function finiteTimestamp(value: string): number | null {
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

/**
 * Deterministic signal-age contract.
 *
 * edgeRemaining is only the remaining fraction of the already-declared signal
 * validity window. It is not win probability, expected return, confidence, or
 * execution authority. The caller must supply the strategy-specific expiresAt
 * generated by the canonical Scanner lifecycle; this service never invents a
 * default validity period.
 */
export function evaluateScannerSignalDecay(input: {
  signalCreatedAt: string;
  expiresAt: string;
  strategyMode?: ScannerStrategyMode | null;
  now?: number;
}): ScannerSignalDecaySnapshot {
  const createdAt = finiteTimestamp(input.signalCreatedAt);
  const expiresAt = finiteTimestamp(input.expiresAt);
  const now = Number.isFinite(input.now) ? Number(input.now) : Date.now();
  const strategyMode = input.strategyMode ?? null;

  if (createdAt == null || expiresAt == null || expiresAt <= createdAt || !Number.isFinite(now)) {
    return {
      signalCreatedAt: input.signalCreatedAt,
      signalAgeMs: 0,
      estimatedHalfLifeMs: 0,
      edgeRemaining: 0,
      expiresAt: input.expiresAt,
      strategyMode,
      state: 'INVALID',
      basis: 'TIME_VALIDITY_ONLY',
      financialProbability: false,
      orderAuthority: false,
    };
  }

  const validityWindowMs = expiresAt - createdAt;
  const signalAgeMs = Math.max(0, now - createdAt);
  const estimatedHalfLifeMs = validityWindowMs / 2;
  const edgeRemaining = clamp((expiresAt - Math.max(now, createdAt)) / validityWindowMs, 0, 1);
  const state: ScannerSignalDecayState = now >= expiresAt
    ? 'EXPIRED'
    : edgeRemaining <= 0.5
      ? 'WEAKENED'
      : 'ACTIVE';

  return {
    signalCreatedAt: new Date(createdAt).toISOString(),
    signalAgeMs,
    estimatedHalfLifeMs,
    edgeRemaining,
    expiresAt: new Date(expiresAt).toISOString(),
    strategyMode,
    state,
    basis: 'TIME_VALIDITY_ONLY',
    financialProbability: false,
    orderAuthority: false,
  };
}
