import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { readVideoResearchReadback } from '../video-research-readback.mjs';

const SHA='a'.repeat(40),DIGEST='b'.repeat(64);
function snapshot(){
 return {runtimeVersion:'video-research-public-provider-runtime-v3',status:'SUCCESS',provider:'YOUTUBE_DATA_API_V3',providerAccess:'OFFICIAL_PUBLIC_API',requestMode:'READ_ONLY_GET',query:'public strategy research',pagesUsed:1,quotaState:'UNKNOWN',credentialConfigured:true,credentialValueExposed:false,sourceCount:1,
 records:[{videoId:'abcdefghijk',canonicalUrl:'https://www.youtube.com/watch?v=abcdefghijk',title:'Public video',channelOrPublisher:'Channel',publishedAt:null,discoveredAt:'2026-10-02T03:00:00.000Z',language:null,durationSec:null,transcriptStatus:'NOT_PROVIDED',captionsKnownPresent:null,sourceTrustTier:'UNKNOWN',contentAuthority:'UNTRUSTED_EXTERNAL_DATA',economicEvidenceCredit:0,profitabilityCredit:0,executionAuthority:'NONE'}],
 safety:{researchOnly:true,economicEvidenceCredit:0,profitabilityCredit:0,executionAuthority:'NONE',paidProviderEnabled:false,scheduleActive:false,automaticDiscoveryEnabled:false,liveTrading:false,privateTradingApi:false,realOrderEnabled:false,credentialMutation:false,transcriptDownloadEnabled:false},
 snapshotProvenance:{schemaVersion:'video-research-sanitized-snapshot-v1',sourceHeadSha:SHA,observedAt:'2026-10-02T03:00:00.000Z',publisherMode:'LOCAL_ATOMIC_FILE',providerRuntimeVersion:'video-research-public-provider-runtime-v3',economicEvidenceCredit:0,profitabilityCredit:0,executionAuthority:'NONE'}};
}
function automation(){
 return {schemaVersion:'research-video-discovery-scan-v1',status:'COMPLETE',observedAt:'2026-10-02T03:00:00.000Z',researchSha:SHA,provider:'YOUTUBE_DATA_API_V3',query:'public strategy research',queryIndex:0,queryCount:4,nextQueryIndex:1,sourceCount:1,snapshotDigest:DIGEST,providerNetworkCalls:1,invocationMode:'SYSTEMD_TIMER',scheduledInvocationObserved:false,reason:null,nextRequiredStep:'SOURCE_REVIEW_THEN_EXISTING_GEMINI_GROQ_ORCHESTRATOR',safety:{researchOnly:true,metadataDiscoveryOnly:true,transcriptDownloadEnabled:false,automaticGeminiExecution:false,automaticGroqExecution:false,automaticAdoption:false,paidFallback:false,economicEvidenceCredit:0,profitabilityCredit:0,executionAuthority:'NONE',liveTrading:false,privateTradingApiAllowed:false,realOrderEnabled:false}};
}
function aiReview(){
 return {schemaVersion:'research-production-ai-scan-v1',status:'COMPLETE',observedAt:Date.parse('2026-10-02T03:00:30.000Z'),researchSha:SHA,provider:'groq',model:'openai/gpt-oss-20b',reason:'CONFIGURED_FREE_ONLY_QUOTA_UNKNOWN',providerNetworkCalls:1,cacheHits:0,invocationMode:'SYSTEMD_TIMER',scheduledInvocationObserved:false,
  reviews:[{profile:'forward',evidenceDigest:'c'.repeat(64),status:'READY',cacheHit:false,role:'CRITIC'}],missingProfiles:[],blockedProfiles:[],deferredProfiles:[],evidenceCredit:0,profitabilityProven:false,champion:null,
  safety:{researchProposalOnly:true,paidFallback:false,executionAuthority:'NONE',numericPerformanceAuthority:false,promotionAuthority:false,championAuthority:false,finalHoldoutOpened:false,orderAllowed:false,liveTrading:false,privateTradingApiAllowed:false,evidenceCredit:0}};
}
const timerProbe=async unit=>({enabled:true,active:true,lastTriggerMs:unit.includes('video-discovery')?Date.parse('2026-10-02T02:59:30.000Z'):Date.parse('2026-10-02T03:00:00.000Z')});

test('missing snapshot stays unknown and never becomes measured zero',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{const r=await readVideoResearchReadback(root);assert.equal(r.available,false);assert.equal(r.dataState,'UNKNOWN');assert.equal(r.executionAuthority,'NONE');}finally{await rm(root,{recursive:true,force:true});}});
test('sanitized snapshot and timer-mode evidence are exposed without credentials or authority',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{await mkdir(join(root,'video-research','current'),{recursive:true});await writeFile(join(root,'video-research','current','video-research-public-provider-runtime-v3.json'),JSON.stringify(snapshot()));await writeFile(join(root,'video-research','latest.json'),JSON.stringify(automation()));await mkdir(join(root,'ai-review'),{recursive:true});await writeFile(join(root,'ai-review','latest.json'),JSON.stringify(aiReview()));const r=await readVideoResearchReadback(root,{probeTimer:timerProbe});assert.equal(r.available,true);assert.equal(r.sourceCount,1);assert.equal(r.automation?.scheduledInvocationObserved,true);assert.equal(r.aiReview?.scheduledInvocationObserved,true);assert.equal(r.aiReview?.reviewCount,1);assert.equal(r.automation?.invocationMode,'SYSTEMD_TIMER');assert.equal(r.economicEvidenceCredit,0);assert.equal(r.profitabilityCredit,0);assert.equal(r.executionAuthority,'NONE');assert.equal(JSON.stringify(r).includes('YOUTUBE_DATA_API_KEY'),false);}finally{await rm(root,{recursive:true,force:true});}});
test('secret-bearing snapshot fails closed',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{await mkdir(join(root,'video-research','current'),{recursive:true});await writeFile(join(root,'video-research','current','video-research-public-provider-runtime-v3.json'),JSON.stringify({...snapshot(),apiKey:'forbidden'}));const r=await readVideoResearchReadback(root);assert.equal(r.available,false);assert.equal(r.reason,'VIDEO_RESEARCH_SNAPSHOT_INVALID');}finally{await rm(root,{recursive:true,force:true});}});

test('unsafe automation receipt is dropped even when snapshot remains measured',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{await mkdir(join(root,'video-research','current'),{recursive:true});await writeFile(join(root,'video-research','current','video-research-public-provider-runtime-v3.json'),JSON.stringify(snapshot()));await writeFile(join(root,'video-research','latest.json'),JSON.stringify({...automation(),safety:{...automation().safety,liveTrading:true}}));const r=await readVideoResearchReadback(root);assert.equal(r.available,true);assert.equal(r.automation,null);assert.equal(r.executionAuthority,'NONE');}finally{await rm(root,{recursive:true,force:true});}});
test('oversized state file fails closed instead of being parsed',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{await mkdir(join(root,'video-research','current'),{recursive:true});await writeFile(join(root,'video-research','current','video-research-public-provider-runtime-v3.json'),' '.repeat(512*1024+1));const r=await readVideoResearchReadback(root);assert.equal(r.available,false);assert.equal(r.reason,'VIDEO_RESEARCH_STATE_UNAVAILABLE');}finally{await rm(root,{recursive:true,force:true});}});

test('timer contract alone never becomes timer proof',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{await mkdir(join(root,'video-research','current'),{recursive:true});await writeFile(join(root,'video-research','current','video-research-public-provider-runtime-v3.json'),JSON.stringify(snapshot()));await writeFile(join(root,'video-research','latest.json'),JSON.stringify(automation()));const r=await readVideoResearchReadback(root,{probeTimer:async()=>({enabled:false,active:false,lastTriggerMs:null})});assert.equal(r.automation?.invocationMode,'SYSTEMD_TIMER');assert.equal(r.automation?.scheduledInvocationObserved,false);}finally{await rm(root,{recursive:true,force:true});}});
test('unsafe AI review is dropped without affecting sanitized video evidence',async()=>{const root=await mkdtemp(join(tmpdir(),'rv-'));try{await mkdir(join(root,'video-research','current'),{recursive:true});await mkdir(join(root,'ai-review'),{recursive:true});await writeFile(join(root,'video-research','current','video-research-public-provider-runtime-v3.json'),JSON.stringify(snapshot()));await writeFile(join(root,'ai-review','latest.json'),JSON.stringify({...aiReview(),safety:{...aiReview().safety,orderAllowed:true}}));const r=await readVideoResearchReadback(root,{probeTimer:timerProbe});assert.equal(r.available,true);assert.equal(r.aiReview,null);assert.equal(r.executionAuthority,'NONE');}finally{await rm(root,{recursive:true,force:true});}});
